# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0004_auto_20180911_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('members', models.ManyToManyField(blank=True, related_name='group', to='social.SocialUser')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
