# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20180911_0138'),
        ('blog', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='social.SocialUser'),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set([('title', 'author')]),
        ),
    ]
