# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('blog', '0009_auto_20180911_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='group.SocialGroup'),
        ),
    ]
