# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.BooleanField(default=False, max_length=1000),
        ),
    ]
