# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20180910_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.BooleanField(default=False),
        ),
    ]
